# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.powernudge: debug
sensor:
  - platform: simulated
    name: "Simulierter Stromverbrauch (W)"
    unit: kw
    amplitude: 3  # Größere Schwankungen für den Tagesverlauf
    mean: 1       # Durchschnittlicher Tagesverbrauch in kWh
    spread: 2      # Zufällige Abweichungen
    seed: 12345    # Für reproduzierbare Ergebnisse


resources:
  - url: /local/apexcharts-card.js?v=2.0.4
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.12.1
    type: module
  - url: /hacsfiles/bar-card/bar-card.js
    type: module