set_ranking_position:
  name: Set Ranking Position
  description: Set Ranking Position of User
  target:
    entity:
      domain: number
      integration: nudgeplatform
  fields:
    ranking_position:
      required: true
    ranking_length:
      required: true